# Streamlit Cloud Deployment Configuration
# This file contains deployment-specific settings for Streamlit Cloud

[deployment]
# Application metadata
app_name = "Reddit Data Scraper"
app_description = "A modern, interactive Reddit data scraper with analytics and intelligent categorization"
app_version = "1.0.0"

# Python configuration
python_version = "3.8"
main_file = "main.py"

# Performance settings
max_upload_size = "200MB"
max_message_size = "200MB"

# Security settings
enable_xsrf_protection = true
enable_cors = false
gather_usage_stats = false

# Caching configuration
cache_ttl = 3600  # 1 hour cache for data fetching
cache_show_spinner = false

# Theme configuration
theme_primary_color = "#FF4B4B"
theme_background_color = "#0E1117"
theme_secondary_background_color = "#262730"
theme_text_color = "#FAFAFA"

# Required secrets for deployment
required_secrets = [
    "REDDIT_CLIENT_ID",
    "REDDIT_CLIENT_SECRET", 
    "REDDIT_USER_AGENT"
]

# Dependencies
python_packages = [
    "praw==7.7.1",
    "python-dotenv==1.1.1", 
    "pandas==2.3.1",
    "streamlit==1.48.1",
    "plotly==6.3.0"
]

# Deployment checklist
deployment_checklist = [
    "✅ Repository is public and accessible",
    "✅ Main file path is set to main.py",
    "✅ Python version is 3.8 or higher",
    "✅ Reddit API credentials are added to secrets",
    "✅ All dependencies are specified in requirements.txt",
    "✅ Security checks have passed",
    "✅ Configuration is optimized for production"
]
